export const SAVE_PASTE = 'SAVE_PASTE';
export const SAVE_PASTE_PENDING = 'SAVE_PASTE_PENDING';
export const LOAD_PASTE = 'LOAD_PASTE';
export const LOAD_PASTE_SUCCESS = 'LOAD_PASTE_SUCCESS';
export const LOAD_ALL_PASTES = 'LOAD_ALL_PASTES';
export const LOAD_ALL_PASTES_SUCCESS = 'LOAD_ALL_PASTES_SUCCESS';
